export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف الغداء",
    price: "60 جنيه",
    category: "غداء",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف العشاء",
    price: "100 جنيه",
    category: "عشاء",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الفطار",
    price: "40 جنيه",
    category: "فطار",
    imgUrl: "4.png",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف الغداء",
    price: "40 جنيه",
    category: "غداء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف العشاء",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "2.png",
  },
];
